### ISSUE TITLE
Django Channels

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/cookiecutter-django-json-api#32]
Should we support Django Channels in some way?

**Comment by sliverc** [comment]
From the README:
> It combines Adfinis best practices in terms of setup, structure and configuration.

I would also like to play around with Django Channels but this cookie cutter template is not meant as a playground but as best practices.

So I guess before we can define best practices we need to play with it in a context of a project.

A nice test case could for be Timed but there needs to be time for this I guess. Closing this but can be introduced once we have a better understanding of it.
